name: test
on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        db:
          [
            { name: SQLite, command: 'npm run test:sqlite' },
            { name: BetterSQLite, command: 'npm run test:better_sqlite' },
            { name: PostgreSQL, needsDocker: true, serviceName: 'pg' },
            { name: Mysql, needsDocker: true, serviceName: 'mysql' },
            { name: MysqlLegacy, needsDocker: true, serviceName: 'mysql_legacy' },
            { name: Mssql, needsDocker: true, serviceName: 'mssql' },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run Tests "${{ matrix.db.name }}"
        if: matrix.db.command
        run: ${{ matrix.db.command }}

      - name: Run Tests "${{ matrix.db.name }}"
        if: ${{ matrix.db.needsDocker }}
        run: DB_SERVICE_NAME=${{ matrix.db.serviceName }} docker-compose -f scripts/docker-compose.yml run lucid
